# Generated by Django 4.1.7 on 2023-04-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_rename_tag_skilltag_remove_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skill_tags',
            field=models.ManyToManyField(blank=True, to='projects.skilltag'),
        ),
    ]
