# Generated by Django 4.1.7 on 2023-04-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_projects_pr_id_a18e17_idx'),
        ('companies', '0003_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='advantage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='number_employees',
            field=models.CharField(blank=True, choices=[('1-10', '1-10'), ('11-50', '11-50'), ('51-100', '51-100'), ('101-500', '101-500'), ('501-1000', '501-1000'), ('1000+', '1000+')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='projects.skilltag'),
        ),
    ]
