# Generated by Django 4.1.7 on 2023-04-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_advantage_company_number_employees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_img',
            field=models.ImageField(blank=True, default='companies/default.jpg', null=True, upload_to='companies/'),
        ),
    ]
