# Generated by Django 4.1.7 on 2023-04-09 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_options_and_more'),
        ('companies', '0005_company_company_img'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyreview',
            unique_together={('company', 'user')},
        ),
    ]
