# Generated by Django 4.1.7 on 2023-05-01 00:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_companyreview_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(blank=True, choices=[('Outsourcing', 'Outsourcing'), ('Product', 'Product')], default='Outsourcing', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='working_time',
            field=models.CharField(blank=True, choices=[('Monday - Friday', 'Monday - Friday'), ('Monday - Saturday', 'Monday - Saturday')], default='Monday - Friday', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companyreview',
            name='culture_stars',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='companyreview',
            name='employee_attention_stars',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='companyreview',
            name='office_starts',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='companyreview',
            name='salary_stars',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='companyreview',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='companyreview',
            name='training_stars',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
