# Generated by Django 4.1.7 on 2023-05-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_alter_company_type_alter_company_working_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cities',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
