# Generated by Django 4.1.7 on 2023-04-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_job_img1_job_job_img2_job_job_img3'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='benefit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='time_work',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('full_time_part_time', 'Full Time or Part Time')], max_length=200, null=True),
        ),
    ]
