# Generated by Django 4.1.7 on 2023-04-06 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_benefit_alter_job_time_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedcv',
            name='job',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
    ]
