# Generated by Django 4.1.7 on 2023-04-04 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_projectcomment_delete_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='SkillTag',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
    ]
