# Generated by Django 4.1.7 on 2023-04-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_name_workexperience_job_title_and_more'),
        ('projects', '0011_project_skill_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='vote_ratio',
        ),
        migrations.RemoveField(
            model_name='project',
            name='vote_total',
        ),
        migrations.AddField(
            model_name='project',
            name='upvote_users',
            field=models.ManyToManyField(blank=True, related_name='upvote_projects', to='users.profile'),
        ),
    ]
