# Generated by Django 4.1.7 on 2023-04-06 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_project_vote_ratio_remove_project_vote_total_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skilltag',
            options={'ordering': ['name']},
        ),
    ]
