# Generated by Django 4.1.7 on 2023-04-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_project_vote_ratio_remove_project_vote_total_and_more'),
        ('users', '0006_rename_name_workexperience_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='projects.skilltag'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='skills',
            field=models.ManyToManyField(blank=True, to='projects.skilltag'),
        ),
    ]
