# Generated by Django 4.1.7 on 2023-04-04 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_delete_jobskill_alter_job_skills'),
        ('users', '0007_profile_skills_workexperience_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
    ]
