# Generated by Django 4.1.7 on 2023-04-06 14:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0013_alter_skilltag_options'),
        ('users', '0008_workexperience_company'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(blank=True, choices=[('intern', 'Intern'), ('fresher', 'Fresher'), ('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior'), ('manager', 'Manager'), ('director', 'Director')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lower_salary', models.IntegerField(blank=True, null=True)),
                ('upper_salary', models.IntegerField(blank=True, null=True)),
                ('time_work', models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('full_time_part_time', 'Full Time or Part Time')], max_length=200, null=True)),
                ('working_model', models.CharField(blank=True, choices=[('office', 'At Office'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('benefit', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('qualification', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('job_img1', models.ImageField(blank=True, default='jobs/default.jpg', null=True, upload_to='jobs/')),
                ('job_img2', models.ImageField(blank=True, default='jobs/default.jpg', null=True, upload_to='jobs/')),
                ('job_img3', models.ImageField(blank=True, default='jobs/default.jpg', null=True, upload_to='jobs/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('levels', models.ManyToManyField(blank=True, to='jobs.joblevel')),
                ('skills', models.ManyToManyField(blank=True, to='projects.skilltag')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='AppliedCV',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cv_files')),
                ('intro', models.TextField(blank=True, null=True)),
                ('job', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
