# Generated by Django 4.1.7 on 2023-04-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='advantage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
