# Generated by Django 4.1.7 on 2023-04-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_advantage'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['id'], name='jobs_job_id_d4da95_idx'),
        ),
    ]
