# Generated by Django 4.1.7 on 2023-04-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_skill_workexperience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperience',
            old_name='name',
            new_name='job_title',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
