# Generated by Django 4.1.7 on 2023-04-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_project_vote_ratio_remove_project_vote_total_and_more'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobSkill',
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(blank=True, to='projects.skilltag'),
        ),
    ]
