# Generated by Django 4.1.7 on 2023-04-05 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_delete_jobskill_alter_job_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.RemoveField(
            model_name='job',
            name='levels',
        ),
        migrations.RemoveField(
            model_name='job',
            name='skills',
        ),
        migrations.DeleteModel(
            name='AppliedCV',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='JobLevel',
        ),
    ]
